/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yeni;

/**
 *
 * @author ebrar
 */
public class skorTablosu extends javax.swing.JFrame {

    /**
     * Creates new form skorTablosu
     */
    public skorTablosu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        d3 = new javax.swing.JTextField();
        d4 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        c4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OZET TABLOSU");
        setLocation(new java.awt.Point(50, 50));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setText("D OYUNCUSU");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(20, 400, 100, 50);

        jTextField2.setEditable(false);
        jTextField2.setText("A OYUNCUSU");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(20, 110, 100, 50);

        jTextField3.setEditable(false);
        jTextField3.setText("B OYUNCUSU");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(20, 200, 100, 50);

        jTextField4.setEditable(false);
        jTextField4.setText("C OYUNCUSU");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(20, 300, 100, 50);

        jTextField5.setEditable(false);
        jTextField5.setText("TOPLANAN ALTIN");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(570, 40, 120, 40);

        jTextField6.setEditable(false);
        jTextField6.setText("ADIM SAYISI");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(150, 40, 100, 40);

        jTextField7.setEditable(false);
        jTextField7.setText("HARCANAN ALTIN");
        jPanel1.add(jTextField7);
        jTextField7.setBounds(270, 40, 120, 40);

        jTextField8.setEditable(false);
        jTextField8.setText("KASADAKI ALTIN");
        jPanel1.add(jTextField8);
        jTextField8.setBounds(420, 40, 120, 40);

        d1.setEditable(false);
        jPanel1.add(d1);
        d1.setBounds(160, 400, 80, 50);

        d2.setEditable(false);
        jPanel1.add(d2);
        d2.setBounds(280, 400, 100, 50);

        d3.setEditable(false);
        jPanel1.add(d3);
        d3.setBounds(430, 400, 100, 50);

        d4.setEditable(false);
        jPanel1.add(d4);
        d4.setBounds(580, 400, 100, 50);

        b1.setEditable(false);
        jPanel1.add(b1);
        b1.setBounds(160, 200, 80, 50);

        a1.setEditable(false);
        jPanel1.add(a1);
        a1.setBounds(160, 110, 80, 50);

        c1.setEditable(false);
        jPanel1.add(c1);
        c1.setBounds(160, 300, 80, 50);

        a2.setEditable(false);
        jPanel1.add(a2);
        a2.setBounds(280, 110, 100, 50);

        b2.setEditable(false);
        jPanel1.add(b2);
        b2.setBounds(280, 200, 100, 50);

        c2.setEditable(false);
        jPanel1.add(c2);
        c2.setBounds(280, 300, 100, 50);

        a3.setEditable(false);
        jPanel1.add(a3);
        a3.setBounds(430, 110, 100, 50);

        b3.setEditable(false);
        jPanel1.add(b3);
        b3.setBounds(430, 200, 100, 50);

        c3.setEditable(false);
        jPanel1.add(c3);
        c3.setBounds(430, 300, 100, 50);

        a4.setEditable(false);
        jPanel1.add(a4);
        a4.setBounds(580, 110, 100, 50);

        b4.setEditable(false);
        jPanel1.add(b4);
        b4.setBounds(580, 200, 100, 50);

        c4.setEditable(false);
        jPanel1.add(c4);
        c4.setBounds(580, 300, 100, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(skorTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(skorTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(skorTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(skorTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new skorTablosu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField a1;
    public javax.swing.JTextField a2;
    public javax.swing.JTextField a3;
    public javax.swing.JTextField a4;
    public javax.swing.JTextField b1;
    public javax.swing.JTextField b2;
    public javax.swing.JTextField b3;
    public javax.swing.JTextField b4;
    public javax.swing.JTextField c1;
    public javax.swing.JTextField c2;
    public javax.swing.JTextField c3;
    public javax.swing.JTextField c4;
    public javax.swing.JTextField d1;
    public javax.swing.JTextField d2;
    public javax.swing.JTextField d3;
    public javax.swing.JTextField d4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
